// <auto-generated />
using System;
using Geometry.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Geometry.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240627173722_Create_Database")]
    partial class Create_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Geometry.Domain.Triangles.Triangle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("SideA")
                        .HasColumnType("double precision")
                        .HasColumnName("side_a");

                    b.Property<double>("SideB")
                        .HasColumnType("double precision")
                        .HasColumnName("side_b");

                    b.Property<double>("SideC")
                        .HasColumnType("double precision")
                        .HasColumnName("side_c");

                    b.HasKey("Id")
                        .HasName("pk_triangles");

                    b.ToTable("triangles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
