version: '3.4'

services:
  geometry.api:
    image: ${DOCKER_REGISTRY-}geometryapi
    container_name: Geometry.Api
    build:
      context: .
      dockerfile: src/Geometry.Api/Dockerfile
    depends_on:
      - geometry-db

  geometry-db:
    image: postgres:latest
    container_name: Geometry.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
